[package]
name = "audio-stream-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
